---
- hosts: all
  connection: local

  vars:
    homebrew_installed_packages:
      - imagemagick
    homebrew_cask_apps:
      - atom
      - docker
      - firefox
      - google-chrome
      - slack

  roles:
    - geerlingguy.homebrew
